export enum ActionTypes {
    // CONTENT LOAD REDUCER
    CONTENT_LOADING = "CONTENT_LOADING",
    CONTENT_VIDEO_LOADING = "CONTENT_VIDEO_LOADING",
    CONTENT_FONT_LOADING = "CONTENT_FONT_LOADING",
    CONTENT_FINGERPRINT_INIT = "CONTENT_FINGERPRINT_INIT",
    CONTENT_REFRESH = "CONTENT_REFRESH",
    CONTENT_LOADING_BAR = "CONTENT_LOADING_BAR",
    CONTENT_SET_VIDEO = "CONTENT_SET_VIDEO",
    CONTENT_IMAGE_LOADING = "CONTENT_IMAGE_LOADING",
    CONTENT_MUSIC_LOADING = "CONTENT_MUSIC_LOADING",
    CONTENT_SET_MUSIC = "CONTENT_SET_MUSIC",

    // GAME REDUCER
    GAME_LOADING = "GAME_LOADING",
    GAME_SET_USER_POINT = "GAME_SET_USER_POINT",
    GAME_REFRESH = "GAME_REFRESH",
    GAME_START_GAME = "GAME_START_GAME"
};
export default ActionTypes;