export enum ActionTypes {
    // CONTENT LOAD REDUCER
    CONTENT_LOADING = "CONTENT_LOADING",
    CONTENT_VIDEO_LOADING = "CONTENT_VIDEO_LOADING",
    CONTENT_FONT_LOADING = "CONTENT_FONT_LOADING",
    CONTENT_FINGERPRINT_INIT = "CONTENT_FINGERPRINT_INIT",
    CONTENT_REFRESH = "CONTENT_REFRESH",
    CONTENT_LOADING_BAR = "CONTENT_LOADING_BAR",
    CONTENT_SET_VIDEO = "CONTENT_SET_VIDEO",

    // AUTH REDUCER
    AUTH_LOADING = "AUTH_LOADING",
    AUTH_USER_TYPE = "AUTH_USER_TYPE",
    AUTH_REFRESH = "AUTH_REFRESH"
};
export default ActionTypes;